[application]
name = "TheoManager"
default_platform = "web"
hot_reload = true

#------------------------------------------
# Web
#------------------------------------------
[web.app]
title = "TheoManager"
[web.resource]
style = []
script = []

[web.resource.dev]
script = []

[web.wasm_opt]
level = "z"

[web.watcher]
index_on_404 = true
watch_path = ["src"]

#------------------------------------------
# Bundler
#------------------------------------------
[bundle]
identifier = "com.MarckFp.theo-manager"
publisher = "MarckFp"
copyright = ""
category = "Utility"
short_description = "An amazing dioxus application."
long_description = """
An amazing dioxus application.
"""

#------------------------------------------
# Windows
#------------------------------------------
[bundle.windows]
allow_downgrades = false
tsp = false
webview_install_mode = {DownloadBootstrapper = {silent = true}}
silent = true
[bundle.windows.nsis]
install_mode = "Both"
display_language_selector = false

#------------------------------------------
# MacOS
#------------------------------------------
[bundle.macos]
hardened_runtime = true
[bundle.macos.files]

#------------------------------------------
# Linux
#------------------------------------------
[bundle.linux]
package_formats = ["deb", "rpm", "appimage"]

#------------------------------------------
# Android
#------------------------------------------

#------------------------------------------
# iOS
#------------------------------------------